### ISSUE TITLE
Add documentation/example for how to support new boards

### ISSUE THREAD

**Issue by cevans01** [kubos/kubos-linux-build#29]
I'm looking at extending this repo's support to a Intel Atom E3800 based SBC. I imagine the steps are something like creating a new directory board/kubos/<new_board> and adding my kernel's config. Having a step by step for how to generate the kernel config files and any other prerequisites might be useful.

**Comment by plauche** [comment]
Hey @cevans01! We are currently working through our documentation and we are planning on working on a porting guide. We do have a community slack where you can talk to our engineers about your porting efforts, I can send you an invite if you'd like.

**Comment by cevans01** [comment]
That would be great, thanks

**Comment by plauche** [comment]
Ok great! We'll send one over. We like to hang out in the kubos channel.
